# Generated by Django 3.2.9 on 2021-12-06 03:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('coffees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 12, 6, 3, 43, 20, 197207, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coffee',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='grinding',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 12, 6, 3, 43, 24, 757619, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grinding',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
